### ISSUE TITLE
Undefined positive flux direction for some Omon variables

### ISSUE THREAD

**Issue by sol1105** [PCMDI/cmip6-cmor-tables#135]
Hello,
The Omon table contains several fluxes that have no defined positive flux direction, eg. [epfe100](http://clipc-services.ceda.ac.uk/dreq/u/5a35e288-c77d-11e6-8a33-5404a60d96b5.html).
The title (or: long_name) specifies "surface downward", however, it is not part of the CV and could be set arbitrarily.
Shouldn't the flux direction be checked by CMOR, as usual, to avoid any confusion later on?
Or is there a reason why this variables are excluded from this check, as they had a defined positive flux direction in CMIP5?
Regards,
Martin

**Comment by dnadeau4** [comment]
@taylor13 @durack1 Can you look at this?

**Comment by durack1** [comment]
@sol1105 this issues are really better raised in the data request repo [cmip6dr/CMIP6_DataRequest_VariableDefinitions](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues) as these tables are derived from the variables defined upstream

**Comment by taylor13** [comment]
@sol1105 The "positive" directive to CMOR enables data providers to specify the direction that they have assumed in fields passed to CMOR.  If their direction is opposite that required by CMIP6 (as specified in the tables), then CMOR will multiply the field by -1, reversing the sign for consistency with the data request.  

The "positive" directive doesn't enable checking for likely errors in sign of the provided data.  Further input on this issue would best be provided via  https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/263 .  If it is likely that some models will save this field as an "upwelling" quantity, rather than a "sinking" quantity (in their original processing before converting through CMOR), then it would probably be helpful to recommend that  the positive direction be explicitly specified in the CMOR tables.

**Comment by taylor13** [comment]
further comment about this should be made at https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/263 so I'll clsoe this issue.
