### ISSUE TITLE
phalf variable is not recognized

### ISSUE THREAD

**Issue by glevava** [PCMDI/cmip6-cmor-tables#146]
From GFDL: phalf variable is not recognized though it's in Data Request.

**Comment by durack1** [comment]
@glevava where is `phalf` defined in the data request? Can you point to the specific html page? http://clipc-services.ceda.ac.uk/dreq/index.html - from a quick search this wasn't found

**Comment by taylor13** [comment]
In several tables this is requested, but it is really only needed, I think, for models where it can't be calculated from the vertical coordinate.  In CMIP5 data providers were requested to:
```
provide this field for models in which the pressure can't be calculated from the
vertical coordinate information stored already for each variable.  Thus, the pressures 
are needed for height or theta-coordinate models, for example, but not sigma- or 
eta-coordinate models.
```
So, for GFDL, I suspect this variable is not needed.  Nevertheless, if GFDL wants to write this variable, they should be able to.  

@glevava What do you mean by "phalf variable is not recognized"?  What happens if you try to write it?

**Comment by glevava** [comment]
From Sergei at GFDL, he doesn't encounter the issue anymore since he updated the cmip6 tables.
Not an issue finally, sorry for the mistake.

**Comment by durack1** [comment]
@glevava thanks for cleaning up and closing!
