### ISSUE TITLE
ua, va have wrong cell_measures in table 6hrLev tagged 01.00.21

### ISSUE THREAD

**Issue by senesis** [PCMDI/cmip6-cmor-tables#162]
For these variables, DREQ 01.00.21 show cell_measures=--OPT and [this page](https://www.earthsystemcog.org/projects/wip/drq_interp_cell_center) provides a clear guideline :

> **6hrLev: ua, va**: this variables are to be used for driving regional models and may either be provided at cell centres or stored as used in the model. The choice is with the data provider. These variables have the cell_measures attribute in the CMORvar record of the data request set to "--OPT". This value should be treated as a directive, the cell_measures attribute of the variable in the NetCDF file should not be set.

However, the CMOR table shows : cell_measures=area: areacella, while PrePARE would need an empty string value

**Comment by taylor13** [comment]
@senesis I just looked at https://github.com/PCMDI/cmip6-cmor-tables/blob/01.00.21/Tables/CMIP6_6hrLev.json, which seem to be consistent with DREQ 01.00.21 because you'll find there cell_measures=--OPT.  Thus, PrePARE should be able to handle this case correctly, I think.  @dnadeau4 does PrePARE bypass checking cell_measures in this case?

**Comment by dnadeau4** [comment]
This is fix now.
8ce88498108f70a13b043ec47146a50c16932fc3

**Comment by dnadeau4** [comment]
https://github.com/PCMDI/cmor/commit/8ce88498108f70a13b043ec47146a50c16932fc3
