### ISSUE TITLE
ap_half_bnds has wrong dimension CMIP6_formula_terms.json

### ISSUE THREAD

**Issue by tommibergman** [PCMDI/cmip6-cmor-tables#229]
Defining ap_half for alternate_hybrid_sigma_half fails due to ap_half_bnds having a dimension of alevel CMIP6_formula_terms.json. As I  understand it should have a dimension of alevhalf.

**Comment by chloemackallah** [comment]
This is not the only half level affected I think.
Processing the variable 'phalf' requires the z-dimension to be 'alevhalf', which in turn required the 'b' z_bounds_factor to be b_bnds. However, in the formula terms, b_bnds has the dimension alevel, not alevhalf. 
This creates a no-win situation where phalf requires its z-dimension to be both alevhalf (as per Amon) and alevel (as per formula_terms).

**Comment by taylor13** [comment]
@tommibergman :  alternate_hybrid_sigma_half are levels located at the bounds of a alternate_hybrid_sigma grid cell, and alternate_hybrid_sigma_half should not have bounds (which is why must_have_bounds = "no" for this coordinate variable).  It is perhaps misleading that in the table, z_bounds_factors are defined; they should probably not be.  Try running CMOR defining alternate_hybrid_sigma_half *without* defining any bounds.  (CMOR will I think ignore z_bounds_factors found in the table.)

@chloemackallah :  None of the half-level vertical coordinates should have bounds (must_have_bounds="no"), so no use should be made of z_bounds_factors (even though they have been defined).  Also please don't change "z_factors"; "b: b" is correct because when b_half is written to the file the name is change from b_half to b (according to the out_name appearing in the table).   And don't change the out_name from "b" to "b_half".

Please let me know if we can close this issues.
thanks,
Karl

**Comment by chloemackallah** [comment]
Hi Karl,
All good now for me, thanks for the help.

Chloe

**Comment by taylor13** [comment]
thanks @chloemackallah .   @tommibergman:  is it o.k. to close this issue?

**Comment by taylor13** [comment]
@tommibergman :  Have you successfully defined alternate_hybrid_sigma_half?

**Comment by tommibergman** [comment]
Sorry, with long vacation and change of institute and country, I have not been able to do a test yet.

**Comment by taylor13** [comment]
@tommibergman :  Just wanted to check on whether you were able to get around this problem?  Or perhaps you gave up?

**Comment by tommibergman** [comment]
Actually, I did this and I can now create phalf on my files. I am now defining ap_half and b_half, which turn into ap and b in the file, as I believe they should. I think that's right, do you agree? Also PrePARE does not complain.

**Comment by mauzey1** [comment]
@taylor13 Should this issue be closed.

**Comment by taylor13** [comment]
Yes.  I think the solution found by the user was the right thing to do.  Thanks.
