### ISSUE TITLE
axes questions

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmip6-cmor-tables#233]
Hi,
I have different questions for axis definitions:
1. `spectband` and `iceband` : 
They have the attribute `"must_have_bounds": "yes" `but neither values nor bounds requested. Does they need to be extended by values and bounds? When variables use this axis type, the axis needs to be registered with `cmor_axis.` If spectband has only one value, CMOR creates a singleton dimension in files for these variables.
2. There is the `plev7c` axis and a lot of `p*` (p560 e.g.) axes which request bounds. Why do they request bounds and the others not? 
3. There is the `plev7` axis defined in CMIP6_coordinate.json which is not in the DReq and not used by any variable :)

Best regards,
Fabi

**Comment by sol1105** [comment]
Regarding point 2: 
For pressure levels, no bounds are requested.
For pressure layers however, bounds are requested.

There is then one inconsistency or at least it is unclear to me how to interpret the following:
For [olayer100m](http://clipc-services.ceda.ac.uk/dreq/u/dim:olayer100m.html):

> bounds: no
> boundsValues: 0. 100.

**Comment by taylor13** [comment]
@sol1105 I have requested that Martin make this chance in the Data Request 01.00.30.  It will then get propagated to the CMOR tables.  Thanks for noticing this.

**Comment by taylor13** [comment]
@wachsylon 
1.  `spectband`and `iceband` indeed `must_have_bounds` but the user is free to specify these according to what makes sense in his/her model, so the DREQ doesn't specify the bounds values.
2.  p220, p560, and p840 are layers used to report certain satellite data on clouds and the measurements correspond to layers with well-defined bounds.  Model output should be reported for these same layers, so these boundsValues are specified in the DREQ.  The ISCCP pressure layers (plev7c) are similar and also have bounds specified.  For all other CMIP6 pressure level data, the data provider can either specify or omit bounds according to their model and whether it is appropriate for any given variable.
3. My understanding is that plev7 is defined because some of the CMOR test codes assumes there is a coordinate of this name.  It is not needed for CMIP6 but is included in the coordinate table for testing purposes.

If these explanations are sufficient, @wachsylon please close this issue.
