### ISSUE TITLE
ssp370 activity_id has two activities in CMIP6_CV.json

### ISSUE THREAD

**Issue by ledm** [PCMDI/cmip6-cmor-tables#264]
Just copying an issue from ESMValTool [(issue 284)](https://github.com/ESMValGroup/ESMValCore/issues/284#issuecomment-538429112).

I think that there's an error in the CMOR table for the experiment SSP3 7.0. 

Looking at the file [`Tables/CMIP6_CV.json`, line 8965](https://github.com/PCMDI/cmip6-cmor-tables/blob/fac4118de2adc20c3184bc02a5d7488b50b9187c/Tables/CMIP6_CV.json#L8965):
```
            "ssp370":{
                "activity_id":[
                    "ScenarioMIP AerChemMIP"
                ],
```

I suspect that the ScenarioMIP and the AerChemMIP activities should not be in the same string, and should either be separated into two strings or into two activities.

**Comment by taylor13** [comment]
According to the first entry in the first table in https://goo.gl/v1drZl, which defines the global attributes, activity_id should be a list of space-separated activities, so I think CMIP6_CV.json is correct as it is now; no edits are needed.  I have noted that in the ESMValTool github issue (https://github.com/ESMValGroup/ESMValCore/issues/284#issuecomment-538429112).

**Comment by valeriupredoi** [comment]
hello @taylor13 cheers muchly for the reply and pointer! But as I look at the example in the table, I see they should be a list of strings separated by commas eg `“CMIP”, “PMIP”,` but the note says they can be merged in single strings separated by spaces eg `“CMIP” “PMIP”`- so which one is it? Is the document using both standards? Cheers :beer:

**Comment by ledm** [comment]
Hi @valeriupredoi, I'm not convinced that there are two standards here. The document says it's a single string with space separators for lists of activities. The example column (`“CMIP”, “PMIP”, “LS3MIP LUMIP” `) shows several valid entries for the `activity` metadata. This is similar in the attributes `realm`, `external_variables` & `conventions`.

A potential inconsistency that I see is that some times in CMOR metadata fields, the space character is also used as part of a single entry, in additional to being used to denote a list. For instance, the term `no parent` is used as a single entry in the `branch method` attribute and the term `50 km` is a valid attribute in the `nominal_resolution` metadata.

Would it not be better to use a dedicated separator character  (maybe `,` or `;`) rather than something like space which is used for several purposes?

**Comment by taylor13** [comment]
Yes, that would be convenient if a certain character invariably signaled "list" in *all* attributes.  That would, of course, rule out that character for any other use.  In any case, at this point we can't change the rules for CMIP6.  In CMIP6 whenever a "space" is used as a separator in a list of items, *all* of the items are single "words" without spaces.  To interpret the attributes, however, you must know which ones may be lists and which may not.

**Comment by wachsylon** [comment]
Hi,
we find that there might be an issue with that entry related to CMOR and the publication workflow. If I try to produce variables with 
`activity_id="AerChemMIP",`
CMOR will not allow that because `ScenarioMIP` is specified first in this CV table.

```
! Warning: Your input attribute "activity_id" with value 
! "AerChemMIP" will be replaced with value "ScenarioMIP AerChemMIP"
! as defined for experiment_id "ssp370".
```
which is O.K. for the attribute BUT the DRS can therefore only be built with ScenarioMIP.

There are modeling groups registered only for AerChemMIP in the CMIP6 CVs. That means they cannot get a data citation for ScenarioMIP data. The ESGF publication workflow builds the publication with the DRS entry which can only be ScenarioMIP if the `activity_id` is given as it is here.

Best,
Fabi

**Comment by wachsylon** [comment]
> Does citation depend on the DRS?

To that extent, that the citation entry is generated from the drs which only includes `ScenarioMIP`. I am in discussion with Martina whether it agrees with citation that the data can be found with the ESGF search engine under AerChemMIP, although there is no citation entry for that MIP.

For CMOR I propose the approach to allow different orders of the list values of `activity_id` .

**Comment by taylor13** [comment]
I don't think this would work because we want software (e.g., I think the publisher does this) to be able to infer the unique DRS value of activity_id from the global attributes in the file.  For ssp370, the DRS activity_id must be ScenarioMIP.  Software can know this by invariably extracting the first value in the list.  

We could consider relaxing this rule, but then software would have to read the experiment_id and consult the [CMIP6_experiment_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json) file to learn what the DRS value of activity_id is. I don't think that is a good idea.

What use case calls for a different ordering?  ScenarioMIP proposed, designed and is responsible for this experiment.  Participants in ScenarioMIP may want to perform it, but it is not primarily a ScenarioMIP experiment.

**Comment by wachsylon** [comment]
@taylor13 

> I don't think this would work because we want software (e.g., I think the publisher does this) to be able to infer the unique DRS value of activity_id from the global attributes in the file

it seems to me that we have software that infers the unique DRS value of the activity_id from the DRS element instead of the global attribute.

> I noticed that a few groups have managed to publish their ssp370 data under only the ScenarioMIP activity, and one group published data only under the AerChemMIP activity (see BCC-ESM1). I

Does that mean that the data should be published for both activities although it is saved just within one element? Right now, there is one citation entry generated for ScenarioMIP for ssp370. Should it also be created for AerChemMIP?

As you can see in the linked CV issue, we have the problem that a ScenarioMIP registration actually requires full participation including submission of all experiments.
