### ISSUE TITLE
CMIP6_CV.json 

### ISSUE THREAD

**Issue by matthew-mizielinski** [PCMDI/cmip6-cmor-tables#29]
The Tables/CMIP6_CV.json appears to be inconsistent with the file of the same name available via https://github.com/PCMDI/cmor/tree/master/TestTables and similar information available via https://github.com/WCRP-CMIP/CMIP6_CVs 

Should we be referring to either of these sources for this particular file or have the recent updates to the mip tables themselves accidentally missed this file?

**Comment by dnadeau4** [comment]
The valid one is the one in cmip6-cmor-tables.  The inconsistency is due to the table name being changed.  I am in a meeting at AMS in Seattle, but I will try to work on this this week.

Denis



Lawrence Livermore National Laboratory
Atmospheric, Earth and Energy Division
925-423-3123

________________________________
From: Matthew Mizielinski
Sent: Monday, January 23, 2017 6:33:46 AM
To: PCMDI/cmip6-cmor-tables
Cc: Subscribed
Subject: [PCMDI/cmip6-cmor-tables] CMIP6_CV.json (#29)


The Tables/CMIP6_CV.json appears to be inconsistent with the file of the same name available via https://github.com/PCMDI/cmor/tree/master/TestTables and similar information available via https://github.com/WCRP-CMIP/CMIP6_CVs

Should we be referring to either of these sources for this particular file or have the recent updates to the mip tables themselves accidentally missed this file?

**Comment by dnadeau4** [comment]
I have a tag  cmor3.2.3 in the cmor repository

**Comment by dnadeau4** [comment]
The latest CMIP6_CV.json tables is now in [here](https://github.com/PCMDI/cmip6-cmor-tables/tree/master/Tables)
