### ISSUE TITLE
Branch for data request v01.00.32

### ISSUE THREAD

**Issue by matthew-mizielinski** [PCMDI/cmip6-cmor-tables#307]
With the release of data request version 01.00.32 it would be good to have a consistent branch/tag of the mip tables to go with this that picks up any of the minor changes in Martin's latest version.

**Comment by durack1** [comment]
@mauzey1 can we prioritize getting these files updated to the latest data request version 0.1.00.32?

As background @matthew-mizielinski is using CMOR 3.4, with the latest tables (currently [`"cmor_version": "3.5",`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_3hr.json#L4). The query raised about cmor_version may be something we'll need to watch as they update to CMOR 3.6 when it lands

@taylor13 ping

**Comment by taylor13** [comment]
@durack1 @mauzey1 As I understand it, the data request version number, which in each "current" CMOR table (e.g., [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Amon.json) ) reads ``"data_specs_version": "01.00.31"`` is independent of the CMOR code version number, which is recorded in the table as ``"cmor_version": "3.5"``. 

 I thought we decided that

1.  the cmor_version number should be set to the oldest (earliest released) CMOR version that would be able to interpret the table.  I think it likely that the earliest version of CMOR that can read current tables is much *older* than 3.5, so CMOR will needlessly throw an error if the tables were read by CMOR version 3.4.  @matthew-mizielinski told us they are using CMOR version 3.4, so I'm not sure how they can read the present CMOR tables without getting an error message.

2.  The data_specs_version should be updated with each new data release.  I don't think CMOR does any checking of this attribute (other than perhaps its format).

3. Nightly (or at least quite often) the CMOR tables would be (automatically) updated in a "nightly" release so modeling groups could obtain the latest tables, independent of CMOR version.  If that is the case, couldn't @matthew-mizielinski get data release 01.00.32 from the nightly repository? Or aren't these nightly releases being produced?

I must be misunderstanding something, but hopefully someone will clear this up for me.

thanks,
Karl

**Comment by durack1** [comment]
Hi Denis, I hope all is well in New Mexico!

Do you have any recall about the below? I vaguely remember that the 3.4 -> 3.5 increment occurred as something meaningful had changed in CMOR and the corresponding tables to warrant the version change, but details are very sketchy to me.

Any memories you have of this would be very useful to our continued tweaks.

Cheers,

P

**Comment by durack1** [comment]
Hi Paul,

Nice to hear from you.  Everything good here in New Mexico,  I got a contractor working on my backyard which create a bit of activities.

Usually I changed version 3.4.0 to 3.4.x where the data request XML file changes.  That used to change very often, and it did not affect running cmor, but would affect the metadata in the resulting HDF5 file.

I would change 3.4.x to 3.5.0 if we add a new Control Vocabulary data structure in the Json file.  This will break a previous version of CMOR since new version of CMOR would expect to find that data structure in the Control Vocabulary file.  Also PrePARE would be broken.

So adding or removing a data structure into CMIP6_CV.json would increase the minor release from 4 to 5.
Changing the data request XML file only would also change CMIP6_CV.json, but only the values, not the data structure so I would do a patch release,  3.4.0 to 3.4.1.

People have to checkout the tables manually and need to look at the release tags.

  1.  CMIP6_CVs-6.2.35.3/DREQ-01.00.31/CMOR-3.5.0
Hope this helps a bit.
Denis




From: "Durack, Paul J." <durack1@llnl.gov>
Date: Tuesday, May 19, 2020 at 9:51 PM
To: PCMDI/cmip6-cmor-tables <reply@reply.github.com>, "Nadeau, Denis" <dnadeau@lanl.gov>
Cc: "Taylor, Karl E." <taylor13@llnl.gov>, "Mauzey, Christopher Francis" <mauzey1@llnl.gov>
Subject: [EXTERNAL] Re: [PCMDI/cmip6-cmor-tables] Branch for data request v01.00.32 (#307)

Hi Denis, I hope all is well in New Mexico!

Do you have any recall about the below? I vaguely remember that the 3.4 -> 3.5 increment occurred as something meaningful had changed in CMOR and the corresponding tables to warrant the version change, but details are very sketchy to me.

Any memories you have of this would be very useful to our continued tweaks.

Cheers,

P

**Comment by durack1** [comment]
Thanks Denis, glad to know you’re doing well in New Mexico and staying safe.

Of course, our cmip6-cmor-tables/CMIP6_CV.json format was hard coded into CMOR, so the 3.4.0 to 3.5.0 was aligned with the format change from a list to a dictionary, thanks for reminding me!

This will be really helpful in moving forward with CMOR patch and feature releases.

Keep safe that side,

P

From: "Nadeau, Denis" <dnadeau@lanl.gov>
Date: Wednesday, May 20, 2020 at 10:51 AM
To: "Durack, Paul J." <durack1@llnl.gov>, PCMDI/cmip6-cmor-tables <reply@reply.github.com>
Cc: "Taylor, Karl E." <taylor13@llnl.gov>, "Mauzey, Christopher Francis" <mauzey1@llnl.gov>
Subject: Re: [EXTERNAL] Re: [PCMDI/cmip6-cmor-tables] Branch for data request v01.00.32 (#307)

Hi Paul,

Nice to hear from you.  Everything good here in New Mexico,  I got a contractor working on my backyard which create a bit of activities.

Usually I changed version 3.4.0 to 3.4.x where the data request XML file changes.  That used to change very often, and it did not affect running cmor, but would affect the metadata in the resulting HDF5 file.

I would change 3.4.x to 3.5.0 if we add a new Control Vocabulary data structure in the Json file.  This will break a previous version of CMOR since new version of CMOR would expect to find that data structure in the Control Vocabulary file.  Also PrePARE would be broken.

So adding or removing a data structure into CMIP6_CV.json would increase the minor release from 4 to 5.
Changing the data request XML file only would also change CMIP6_CV.json, but only the values, not the data structure so I would do a patch release,  3.4.0 to 3.4.1.

People have to checkout the tables manually and need to look at the release tags.

  1.  CMIP6_CVs-6.2.35.3/DREQ-01.00.31/CMOR-3.5.0
Hope this helps a bit.
Denis




From: "Durack, Paul J." <durack1@llnl.gov>
Date: Tuesday, May 19, 2020 at 9:51 PM
To: PCMDI/cmip6-cmor-tables <reply@reply.github.com>, "Nadeau, Denis" <dnadeau@lanl.gov>
Cc: "Taylor, Karl E." <taylor13@llnl.gov>, "Mauzey, Christopher Francis" <mauzey1@llnl.gov>
Subject: [EXTERNAL] Re: [PCMDI/cmip6-cmor-tables] Branch for data request v01.00.32 (#307)

Hi Denis, I hope all is well in New Mexico!

Do you have any recall about the below? I vaguely remember that the 3.4 -> 3.5 increment occurred as something meaningful had changed in CMOR and the corresponding tables to warrant the version change, but details are very sketchy to me.

Any memories you have of this would be very useful to our continued tweaks.

Cheers,

P

**Comment by durack1** [comment]
@matthew-mizielinski taking a quick scan through this, it seems like it's very old news, with no ongoing requirements for CMOR development, so will close - if this is an issue that remains for CMOR4 dev, please reopen
