### ISSUE TITLE
COVID Exps

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmip6-cmor-tables#326]
Hi,
there are some new COVID experiments in the CVs, e.g. "ssp245-cov". We require an update of the cmip6-cmor-tables. Maybe we should also wait for a new DReq version since the exps must be included there as well.
Best,
Fabi

**Comment by taylor13** [comment]
I think these already are were added to https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json     a couple of days ago.   (I think only the 6 most important experiments have been added; they are considered part of the DAMIP activity so that the infrastructure can handle it.  CovidMIP is not an authorized CMIP6 activity and so does not appear in the activity_id CV.  There are no new variables requested for these new experiments, so you should be able to write anything requested using the current CMOR tables.)
 Let us know if something is missing or you encounter any problems.

**Comment by wachsylon** [comment]
Thanks Karl for the quick answer. We can work with the CV, but in my opinion it would be nicer to have a new release of the tables because the quality assurance should not need to relie on a git commit but rather on a release name.
Best,Fabi

**Comment by taylor13** [comment]
@mauzey1 @durack1 :  what is our policy for new table releases vs. commits?  Seems like we discussed this at some length a long time ago.

**Comment by durack1** [comment]
@wachsylon the [releases](https://github.com/PCMDI/cmip6-cmor-tables/releases) have been generated in the past to deal with CMOR changes which require minimum versions of tables, or secondarily for updates to the data request from which the cmip6-cmor-tables are built.

As @taylor13 notes the [CMIP6_CV.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json) is updated nightly by cronjob, and we have not been issuing new releases when these updates occur, rather the git commit is how this has been tracked

**Comment by wachsylon** [comment]
I rethought my point. I agree that it is necessary to use the most recent CMIP6_CV.json although working with old tables which means that there is no need for a new release.

The question then is
Why CMIP6_CV is included at all in the tables as a static file? However, I right now do not have an alternative suggestion :) Sorry.

You can close that issue.

**Comment by durack1** [comment]
To close this out, the [CMIP6_CV.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json) file is included in the repo for user ease, we have considered plans to also include future CVs (such as a potential CMIP6Plus_CV.json) which would leverage the CMIP6-version tables, but allow a post-CMIP6 experiment/cohort to develop.

Obviously, for CMIP7 many things would need updating, and so cmip7-cmor-tables, and a complete rethink may be necessary at that time
